### ISSUE TITLE
Find a way to test locally by spinning up our own non-cloud db (Postgres, SQLlite...)

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#10]
We'll want to be able to test our stuff and it might be a good idea to make sure we can spin up a local db against which to test our stuff.

I think it's possible to make a postgresDB locally (and in github actions for testing). If this is too complex, we should be able to spin up a sqllite db but the SQL it can run is a bit shitty. Postgres looks more like main cloud dbs such as Snowflake, BigQuery and Redshift.

**Comment by bastienboutonnet** [comment]
Looks like there are some github actions and documentation on how to set up a postgres db to do integration testing in git hub actions:
https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers

**Comment by bastienboutonnet** [comment]
And here is a pytest plugin to hook up tests to a postgres db: https://pypi.org/project/pytest-postgresql/

**Comment by virvirlopez** [comment]
Creating  a test database in postgres:
https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb

**Comment by virvirlopez** [comment]
Redshift is going to be difficult, because we need a license, but we can use the demo account. https://www.redshift3d.com/demo

**Comment by bastienboutonnet** [comment]
Yeah Postgres is totally doable locally or using `pytest` fixtures from what I have seen. Also in this comment: https://github.com/bitpicky/dbt-sugar/issues/9#issuecomment-749227332 I mentioned that this package is using the dbt connectors and if we went down that route (which I think we should seriously consider) then we could use most of the testing infra that is set up like the docker files etc. 

But I think we need to look into it together and put down all the pros and cons.

**Comment by bastienboutonnet** [comment]
Regarding the redshift demo you linked, it looks like it's a version of redshift that is GPU powered and requires some NVIDIA drivers and I'm not sure if any of us have it or if it would be easy to set up in a docker container. For example this is what my laptop graphic hardware looks like:
```
Intel Iris Plus Graphics 655:

  Chipset Model:	Intel Iris Plus Graphics 655
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3ea5
  Revision ID:	0x0001
  Metal:	Supported, feature set macOS GPUFamily2 v1
```

**Comment by bastienboutonnet** [comment]
There seems to be a way to get a trial version of Redshift btw but it's limited to 2 months and subject to eligibility which I think we would qualify for but yeah it's not ideal: https://aws.amazon.com/redshift/free-trial/

Since I think we will be using fairly basic queries such as selecting table info or metadata, maybe we don't have to worry too much about testing but that will be annoying.

My feeling, is that we could provide support for the dbs we can support and let people write and develop their own plugins to connect to other databases if they can test them. Or rely on the dbt adaptors which will be tested for the dbs we'd want to support (i.e. the big 4 cloud dbs).
