### ISSUE TITLE
Testing: Fix and improve tasks

### ISSUE THREAD

**Issue by virvirlopez** [bitpicky/dbt-sugar#124]
- Stop the process at any time.

**Comment by bastienboutonnet** [comment]
When we cannot find a dbt project we get this:
```bash
dbt_sugar.core.exceptions.MissingDbtProjects:
The following dbt projects are missing: 
['dbt_sugar_test']
```

We should make this more helpful

**Comment by bastienboutonnet** [comment]
look to see if we can avoid wrapping the validation errors
```bash
pydantic.error_wrappers.ValidationError:
[ErrorWrapper(exc=MissingError(), loc=('port',))]
<class 'dbt_sugar.core.clients.dbt.PostgresDbtProfilesModel'>
```

**Comment by bastienboutonnet** [comment]
path not printed
```bash
dbt_sugar.core.exceptions.ProfileParsingError:
Could not read database type for dbt_sugar_test in the profiles.yml located in .
```

**Comment by bastienboutonnet** [comment]
print the profile file path would be helpful
```bash
dbt_sugar.core.exceptions.ProfileParsingError:
Could not find an entry for target: postgres, under the dbt_sugar_test config.
```

**Comment by virvirlopez** [comment]
Bug: when a column doesn't have a description is failing, and it should not, it should take the description as a not description for this column yet.

**Comment by virvirlopez** [comment]
Bug: when a column has a string TAG, added as a list, not each character as a value.

**Comment by virvirlopez** [comment]
If the model doesn't have the column key it doesn't add the columns.

**Comment by virvirlopez** [comment]
BUG: if the description doesn't exists and we added it after creating the model, is in the wrong position.

**Comment by virvirlopez** [comment]
Feature: Alert if the model is duplicate in a schema.yml.

**Comment by virvirlopez** [comment]
- Fix: when the user does not enters any tag don't save the tags. (don't add if empty string)
