### ISSUE TITLE
[bug] when user aborts we need to clean up

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#140]
This is a bit related to the first message in #124 which should address a `ctrl + c` user abort in one go rather than going through the rest of the prompts.

When user aborts for now we still end up potentially modifying their yamls which is a bit awkward and maybe even dangerous.

We should think of a way to kick in a clean up task which unmodifies what we have changed or we should hold off updates until we get a clear signal that the task has completed successfully. In a way it's actually a bit weird that we change users yamls as we go along but maybe there is no other way to do it especially for test addition but for this one we definitely have a way to clean up so I feel we should be able to do so for column descriptions as well as tags.

@virvirlopez what do you think?

**Comment by virvirlopez** [comment]
I like the idea, I think that we should implement an exit command, every time that the user writes exit, it will save and exit the process. What do you think?

**Comment by bastienboutonnet** [comment]
What do you mean by write user writes exit? @virvirlopez
