### ISSUE TITLE
Snowflake connector has no option to pass warehouse name

### ISSUE THREAD

**Issue by sphinks** [bitpicky/dbt-sugar#204]
Looks like there is no option to pass warehouse name to snowflake connection and also I do not see that it could be optained from dbt profile by code. I try to run dbt sugar and get such error:

```
error_value: {'msg': "No active warehouse selected in the current session.  Selec... [237]connection: <snowflake.connector.connection.SnowflakeConnection object at 0x7f52bb92d990>
cursor: <snowflake.connector.cursor.SnowflakeCursor object at 0x7f52bbdf9390>
```

The way I call it 

```dbt-sugar doc --config-path ./ --profiles-dir ./ -m model -t snowflake-dev```

**Comment by bastienboutonnet** [comment]
Hi @sphinks! First of all thanks a lot for giving a try to the tool this helps us a lot! 

dbt-sugar reads the profile info directly from your dbt `profiles.yml` or from your CLI argument (although I need to double check that that works for sure but that's the intention) so as long as that's present where you point it to that should be fine. 

From what I see, although I have a schema expectation here that does include and expect `warehouse` here: https://github.com/bitpicky/dbt-sugar/blob/main/dbt_sugar/core/clients/dbt.py#L32-L42

It looks like when we create the connection we actually don't pass that at all: https://github.com/bitpicky/dbt-sugar/blob/main/dbt_sugar/core/connectors/snowflake_connector.py 🤦 

Just to make sure of a few things, could you copy the content of your `sugar_config.yml` here?

Also, looking at your call if you were to get passed the database connection issue you'd run into an issue that you are not providing a model to document.

dbt-sugar need to run with a `--model/-m model_name` argument. I'm actually surprised the argument parser didn't complain already... (I'll also double check this).

In the meantime I'll revise the connector code. Unfortunately, I do not have access to a snowflake warehouse anymore but you might be able to help me test it if you're confortable setting up a venv and installing the patch in "editable" mode. If not, I'll see if I can pester @virvirlopez to test it out on snowflake.

**Comment by bastienboutonnet** [comment]
ok @sphinks I have a patch that I **think** should fix the issue if it was just due to our forgetting to create the URL with the warehouse parameter.

If you're able to test it, you could check out the code that's in that branch: https://github.com/bitpicky/dbt-sugar/pull/205

- Create a venv and activate it
- clone the repo
- check out the branch
- cd to where you cloned the repo and make sure you're at the root of the dbt-sugar repo `pip install .` this will install the tool from the code as it sits in the branch.

If you can't/don't want to test it, i'll see if I can get someone with a snowflake warehouse to try it.

Still interested in double checking your `sugar_config.yml` though to make sure all is peachy.

**Comment by sphinks** [comment]
@bastienboutonnet I can give it a try. Will do it a little bit later today and return to you with result. Thanks for hotfix!

**Comment by bastienboutonnet** [comment]
@sphinks amazing. Let me know if I can help. Don't know how comfortable you are with the install instructions above. To some it would be oh yeah no brainer and to others it might be really daunting since I don't know what your background is I don't want to assume too much :)

**Comment by sphinks** [comment]
My sugar_config is pretty simple:

```
defaults:
  syrup: syrup_1
  target: dev
syrups:
  - name: syrup_1
    dbt_projects:
      - name: dbt_test1
        path: "./"
        excluded_tables:
          - table_a
```

**Comment by bastienboutonnet** [comment]
OK config looks ok.

Good point depending how you installed dbt-sugar (curious which install you went for) then maybe that one is taking over. 

What does `which dbt-sugar` tell you?

**Comment by bastienboutonnet** [comment]
thinking of it, if you followed the recommended install option (https://bitpicky.gitbook.io/dbt-sugar/installation-and-configuration/installation-and-update#install-using-pipx-strongly-recommended) then you probably installed via pipx which I think takes over even a venv

pipx has editable install too `--editable`

alternatively you could just point it to the bin of your venv something like
```
/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.8/bin/dbt-sugar doc -m ...
```

**Comment by sphinks** [comment]
@bastienboutonnet managed to run patched version. You are right pipx takes over python env. You patch is working like a charm! I was able to get to documentation menu without any issue!

**Comment by bastienboutonnet** [comment]
Yay! So happy! Ok I'll merge it and cut a new release tomorrow morning. 

Thanks for trying it out!

**Comment by bastienboutonnet** [comment]
@sphinks I pushed a release earlier yesterday so if you want to flip back to using the install via pipx you should be able to do `pipx upgrade dbt-sugar`

Let me know if you run into any other issue but I hope you don't and thanks once again for trying out the app and reporting the bug!

**Comment by sphinks** [comment]
@bastienboutonnet cool! Thank you!
