### ISSUE TITLE
Hide password on dbt-sugar logs

### ISSUE THREAD

**Issue by ldbrandi** [bitpicky/dbt-sugar#272]
Hello!

There is a `read_profile` line on the dbt-sugar logs that is currently showing the credentials. Can we hide the password? It's safer to avoid printing this kind of information. 

Thank you!

**Comment by bastienboutonnet** [comment]
Thanks for reporting this issue @ldbrandi 

I totally agree with you on this. I'll look into it as soon as I can squeeze a few minutes.

Out of curiousity:
I imagine those show up in the log files or when you run dbt-sugar with `--log-level debug` correct?

The solution would be to add something in the logger that sanitises any dict or string that comes in after the word "password" or so. There are hacky ways or maybe more out of the box ways by using some libraries that do that. 

I'll have to do some research, however, if you already know of such things feel free to point me to anything.

**Comment by bastienboutonnet** [comment]
Documents that can help:
https://relaxdiego.com/2014/07/logging-in-python.html

**Comment by bastienboutonnet** [comment]
`(?<=password=)([^\s]+)` this regex will probably sort of work unless there is a space in the string?

**Comment by bastienboutonnet** [comment]
This might also work provided the dict that holds the creds is always ordered so that password comes before database and is separated by a space
`(?<=password=).*(?= database)`

I might have a way of genericising that it be any word precedded by a space and followed by an =
