### ISSUE TITLE
Missing Target CLI Flag in 2 of 3 Commands

### ISSUE THREAD

**Issue by z3z1ma** [bitpicky/dbt-sugar#346]
**Describe the bug**
Target is not passed as a CLI arg to all commands. This causes dbt-sugar to fallback to using the default target. My default target is dev but I want to run dbt-sugar for prod target. This is not optimal. We should add target to all commands.

![image](https://user-images.githubusercontent.com/41213451/134707118-5d163f07-1993-46a4-bc22-a93dea24ad5b.png)

In the above screenshot we can clearly see where, if target is provided, it is consumed but because it cant be provided in 2 of the 3 commands, they can only ever run with default profile. 

I am already working on a PR which should be up in a few minutes.

**Comment by z3z1ma** [comment]
Side note, why don't we just use click for managing the CLI and arguments etc? 
I noticed it installed during poetry dependency resolution too. 

It even has a CliRunner which is specifically purposed for testing cli tools with pytest.

**Comment by bastienboutonnet** [comment]
Thanks @z3z1ma for this. I'll take a look at the PR.

Regarding using click. I am not a fan of it and how it looks in the code in general. However, if it would deal with the duplication then maybe its worth looking into. Do you have some documentation pointers that could show me how it would address the todo you're referring to? Cos that could be interesting.

**Comment by z3z1ma** [comment]
I have personally used this something along the lines of this below with some success. You could keep it separate in a click_helper module like you have yaml_helper if you dont want the decorator seen in your main module. Honestly click is fast to develop and has what is a lot less boiler plate to maintain than argparse IMO. My current thoughts at least.

But here is the snippet

```python
# You can import this from a `click_opts` module and separate it from your code if you want but if you don't have many shared opts its probably fine
def common_params(func):
    @click.option('--foo')
    @click.option('--bar')
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper


@click.command()
@common_params
@click.option('--baz')
def cli(foo, bar, baz):
    print(foo, bar, baz)
```


Closing this since we resolved the issue.

**Comment by bastienboutonnet** [comment]
Thanks for the snippet @z3z1ma I guess, it could be something to revisit one day and I agree there are some pros and cons in all approaches.
