### ISSUE TITLE
[BUG] ERROR: Could not find a version that satisfies the requirement dbt-sugar (from versions: none)

### ISSUE THREAD

**Issue by jdavid459** [bitpicky/dbt-sugar#380]
**Describe the bug**
Apologize if I'm missing something obvious here.

I ran pip install dbt-sugar and I'm getting the following response:

> ERROR: Could not find a version that satisfies the requirement dbt-sugar (from versions: none)
> ERROR: No matching distribution found for dbt-suga

**To Reproduce**
Steps to reproduce the behaviour:

1. pip install dbt-sugar

**Expected behaviour**
dbt-sugar to download

I'd also note that I can download other packages via pip with no issue.
- OS: [e.g. iOS] Macbook M1 12.01
- python 3.10.0
- pip-21.3.1

Thanks!

**Comment by bastienboutonnet** [comment]
Hi @jdavid459 no worries that was the right move. Somehow I have a requirement that Python be <3.10 (https://github.com/bitpicky/dbt-sugar/blob/main/pyproject.toml#L23)

I'll have to give it a go on 3.10 and relax the constraint, I don't remember there being a problem. Is there any chance you can run it in a 3.9 env in the meantime until I push a change?

I should be able to find some time to try this out in the coming day or so.

**Comment by bastienboutonnet** [comment]
Hi again @jdavid459 looks like the test suite worked fine with python 3.10 so I'll go ahead and cut a new release in a bit. 

Let me know if you get a chance to make it install when you get round to it!
