### ISSUE TITLE
should we allow users to deactivate tags and/or tests questioning in the config/CLI?

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#81]
I'm thinking some users may not want to use tags or, god forbids, tests.

Would it make sense to maybe have a CLI arg + a sugar_config option which would be something like
`skip_tags: True` (or `skip_tests: True`) which would skip dbt-sugar asking if users want to add tags or tests?

@virvirlopez how easy do you think it would be to skip tag or test adding in your backend control flow if you had access to those flags from the `DbtSugarConfig` object?

**Comment by virvirlopez** [comment]
Yes, I think that it will be a great idea to create a "define" command, that you can change the setup of the test and tags. Also, will be nice to have a parameter in the command model. Imagine that normally you don't put TAGs or tests but for one model you want. What do you think Bastien?

**Comment by bastienboutonnet** [comment]
Thanks @virvirlopez for your thoughts.

I think rather than adding a new command, I would prefer allowing users to pass `--no-tests` and `--no-tags` to the CLI call as well as into the `sugar_config.yml` if they want to deactivate test and tags adding for all runs no?

**Comment by virvirlopez** [comment]
Yes, of course! That sounds great to me! We can add to this one if you want.
