### ISSUE TITLE
What would be the best way to connect to various dbs?

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#9]
The core ability for `dbt-sugar` to generate documentation is to be able to generate new yaml files from the model's columns. For this it needs to be able to talk to databases and either:
- query for the columns of the current model
- or query the entire information schema of a certain db (some databases might or might not have that concept and we'll probably want to make our own abstractions for this)

@virvirlopez and I discussed that we will likely want to build some connectors (or at least an abstaction layer) but we might also be able to leverage [`dbt`'s](https://github.com/fishtown-analytics/dbt) own adapter functions as `dbt` already knows how to talk to many databases and has adaptors for them.

The issue with relying on `dbt`'s adaptors is that they may break or change a lot until they release a stable API in `v1` so we'll have to do some reasarch.

The good thing is that if we at least write our abstraction layer we'll be able to either go all the way and write our own connectors or we'll be able to replace any broken or changed adaptor fairly quickly. Also, it's probably a good idea not to have too many dependencies.

@virvirlopez feel free to drop some of your thoughts on here and whatever comes out of our research

**Comment by bastienboutonnet** [comment]
@virvirlopez as a follow up to this. I also wrote `sheetwork` with a connector design in mind. It may not be the best but that's something we could steal from also:

https://github.com/bastienboutonnet/sheetwork/tree/main/sheetwork/core/adapters

The main thing, from a user perspective is that we might want to not have to require them to create YET another profile and credentials file. So if we hooked up to dbt's profile or looked into getting credentials from their code this might give us what we need.

I looked a bit at the adaptors from `dbt` and they are quite "complex" if we just want to run a simple `select` to get the columns from a model although down the line if we also want to write they might definitely be useful.

What are your thoughts since you have a much better eye for this kind of things?

**Comment by bastienboutonnet** [comment]
@virvirlopez here's another update.

I forgot about that tool I contributed to a while ago. But they have a `bootstrap` task which generates a boilerplate `schema.yaml` file with the name of the columns of a given model by reading from the dbs using the `dbt` adaptors.

I'm thinking maybe we could do something similar if we don't want to write our own connectors?

Here's the code for the `bootstrap` task: https://github.com/mikekaminsky/dbt-helper/blob/2d209ad151ef588519605dbe1031ca4bf8455ca2/core/bootstrap.py

**Comment by virvirlopez** [comment]
Don't fully like to use the python API because they say that is no stable https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api/

**Comment by virvirlopez** [comment]
We need to create support for:
- BigQuery.
- Postgres.
- Redshift.
- Snowflake.

**Comment by bastienboutonnet** [comment]
@virvirlopez Yeah I know that it is liable to changes. We might want to think about how to do a back up for things. Or just create our own and wait to use theirs until when the API is more stable.

One challenge is that we won't be able to test our connectors in any of the dbs other than Postgres (and snowflake) which worries me a bit.

One thing we'll have and want to do is to rely on dbt's profiles ideally, because I don't really want to ask users to set up yet another set of credentials?

What do you think?

**Comment by bastienboutonnet** [comment]
For posterity, I'm going to record the summary of our decision here:
Because we don't want to ever run into the case where the `dbt` API breaks on us until it is stable and because our connectors only need to run very simple operations we'll develop our own this means:
- we'll develop for postgres, which we can test locally
- we'll develop for snowflake, which we have access to.

Other connectors (for example to BQ and Redshift could either be developped by other poeple who have access to it) or by copying some of the lower level stuff that dbt does with them and not test it.

We might be able to get an AWS Redshift trial if we really want to.

**Comment by bastienboutonnet** [comment]
Closing this discussion issue in favour of the more concrete implementation one #15
